[package]
name = "range-cmp"
version = "1.0.0"
edition = "2018"
rust-version = "1.35"
license = "MIT OR Apache-2.0"
description = "Trait that allows comparing a value to a range of values"
repository = "https://github.com/Akvize/range-cmp"
readme = "README.md"
keywords = ["range", "comparison", "ordering", "ord", "cmp"]
categories = ["algorithms", "no-std", "rust-patterns"]
exclude = [
    "pre-commit",
    "CONTRIBUTING.md",
]

[dependencies]
